version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "${VITE_PORT}:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.backend
    ports:
      - "${SERVER_PORT}:3001"
    env_file:
      - ../.env
    environment:
      - SERVER_PORT=3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
